### ISSUE TITLE
Cannot use bluetooth headset to fast forward 30 seconds

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-android#35]

**Comment by sanky10987** [comment]
@crablar 
I have the fix for this, but I do not have access to commit on 'develop' branch. Should I create a new branch?

overriding the increment speed for MediaSessionConnector at the end

Fix looks as below
` 
            //override media connector increment speed
            val incrementMs = resources.getInteger(R.integer.increment_ms)
            setFastForwardIncrementMs(incrementMs)
            setRewindIncrementMs(incrementMs)
            setPlayer(exoPlayer)
        }`

**Comment by crablar** [comment]
@MostafaGazar  could you take a look?

**Comment by MostafaGazar** [comment]
Thanks @sanky10987 for looking into this. Can you please:
- Fork this project.
- Create your feature branch based off the develop branch.
- Create a pull request to get your work reviewed and merged back into the upstream develop branch.

You can find a full set of [instructions here](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-android/pull/38)

**Comment by sanky10987** [comment]
@MostafaGazar Here you go https://github.com/SoftwareEngineeringDaily/software-engineering-daily-android/pull/41
