### ISSUE TITLE
Migrate to a progressive webapp

### ISSUE THREAD

**Issue by DGKSK8LIFE** [SoftwareEngineeringDaily/software-engineering-daily-android#44]

**Comment by DGKSK8LIFE** [comment]
why was this closed? @MostafaGazar

**Comment by MostafaGazar** [comment]
It did not have any details about why this was added and how it would be done.

**Comment by DGKSK8LIFE** [comment]
Would you like me to elaborate? @MostafaGazar The reason I opened this is because Jeff mentioned a few months ago that there was feature disparity between the ios and android SE daily apps. My suggestion is that we incrementally rewrite the mobile codebase in react native.
